### ISSUE TITLE
Unbound Slot  NAME in keychoard-editor.lisp on CCL

### ISSUE THREAD

**Issue by vr3dc** [Shinmera/qtools#1]
Slot CCL::NAME is unbound in #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x5546CEF6>
   [Condition of type UNBOUND-SLOT]

This happened when quickloading QTools specifically in keychord-editor.lisp

I have loaded it before and had it work. I understand that you are updating constantly. I figured that you might easily find the misstep.

Thanks again for your excellent library.

Pat ODonnell

**Comment by Shinmera** [comment]
Cannot replicate on CCL 1.10-r16196 Linux x64, qtools 51b986e12016b0c64e8b806aee66a65359999009 .

What version and OS are you on?

**Comment by vr3dc** [comment]
CL-USER> (lisp-implementation-version)
"Version 1.9-r16345M  (LinuxARM32)"


Slot CCL::NAME is unbound in #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x5546CEF6>
   [Condition of type UNBOUND-SLOT]

Restarts:
 0: [USE-VALUE] Return a value
 1: [LOAD-SOURCE] Load "home:quicklisp;local-projects;qtools;keychord-editor.lisp" instead of "/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl"
 2: [RECOMPILE] Compile "home:quicklisp;local-projects;qtools;keychord-editor.lisp" into "/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl" then load "/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl" again
 3: [RETRY-LOAD] Retry loading #P"/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl"
 4: [SKIP-LOAD] Skip loading #P"/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl"
 5: [LOAD-OTHER] Load other file instead of #P"/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl"
 --more--

Backtrace:
  0: (#<CCL::STANDARD-KERNEL-METHOD SLOT-UNBOUND (T T T)> ((#<RESTART CCL::LOAD-SOURCE #xB55C5FBE> #<RESTART CCL::RECOMPILE #xB55C5FE6>) ..))) 188 ((#<RESTART USE-VALUE #xB55C4346>) ..))))
  1: (#<CCL::STANDARD-KERNEL-METHOD SLOT-UNBOUND (T T T)> #<STANDARD-CLASS QTOOLS:WIDGET-CLASS> #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x5546CEF6> CCL::NAME)
  2: ((:INTERNAL CCL::%XERR-DISP))
  3: (NIL #<Unknown Arguments>)
  4: (CCL::FUNCALL-WITH-ERROR-REENTRY-DETECTION #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%XERR-DISP) #xB55C43BE>)
  5: (NIL #<Unknown Arguments>)
  6: ((:INTERNAL CCL::%XERR-DISP) -313061114)
  7: (NIL #<Unknown Arguments>)
  8: (CCL::FUNCALL-WITH-XP-STACK-FRAMES 2 -313061016 #<Compiled-function CCL::%XERR-DISP (Non-Global)  #x541C3D9E>)
  9: (CCL::%MAYBE-STD-SLOT-VALUE-USING-CLASS #<STANDARD-CLASS QTOOLS:WIDGET-CLASS> #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> #<STANDARD-EFFECTIVE-SLOT-DEFINITION for instance s..
 10: ((:INTERNAL (PRINT-OBJECT (CLASS T))))
 11: (CCL::%PRINT-UNREADABLE-OBJECT #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> #<STRING-OUTPUT-STREAM  #x55429BC6> NIL NIL #<COMPILED-LEXICAL-CLOSURE (:INTERNAL ..))
 12: (NIL #<Unknown Arguments>)
 13: (#<CCL::STANDARD-KERNEL-METHOD PRINT-OBJECT (CLASS T)> #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> #<STRING-OUTPUT-STREAM  #x55429BC6>)
 14: (NIL #<Unknown Arguments>)
 15: (CCL::%CALL-NEXT-METHOD[error printing frame]
 16: (CCL::%CALL-NEXT-METHOD (NIL #<CCL::STANDARD-KERNEL-METHOD PRINT-OBJECT (CLASS T)> . -313422587))
 17: (NIL #<Unknown Arguments>)
 18: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<CCL::STANDARD-KERNEL-METHOD PRINT-OBJECT :AROUND (T T)> #<CCL::STANDARD-KERNEL-METHOD PRINT-OBJECT (CLASS T)>) -313422587)
 19: (NIL #<Unknown Arguments>)
 20: (NIL #<Unknown Arguments>)
 21: (NIL #<Unknown Arguments>)
 22: (CCL::WRITE-A-FROB #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> #<STRING-OUTPUT-STREAM  #x55429BC6> 536870911 NIL)
 23: (CCL::WRITE-INTERNAL #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::HANDLER CCL::WRITE-INTERNAL) #xB55C4DA6> (ERROR #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::HANDLER CCL::WRITE-INTERNAL) #xB55C4DA6>) ((T..
 24: (CCL::WRITE-INTERNAL #<STRING-OUTPUT-STREAM  #x55429BC6> #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> 536870911 NIL)
 25: (CCL::WRITE-1 #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> #<STRING-OUTPUT-STREAM  #x55429BC6> 536870911)
 26: (NIL #<Unknown Arguments>)
 27: (PRIN1 #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> #<STRING-OUTPUT-STREAM  #x55429BC6>)
 28: (NIL #<Unknown Arguments>)
 29: (CCL::FORMAT-PRIN1 #<STRING-OUTPUT-STREAM  #x55429BC6> NIL NIL)
 30: (CCL::SUB-FORMAT #<STRING-OUTPUT-STREAM  #x55429BC6> 1 31)
 31: (CCL::DO-SUB-FORMAT NIL)
 32: (CCL::DO-SUB-FORMAT NIL)
 33: (CCL::DO-SUB-FORMAT #<STRING-OUTPUT-STREAM  #x55429BC6>)
 34: (FORMAT #<STRING-OUTPUT-STREAM  #x55429BC6> "~s Delegating class options: ~s" #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> (:NAME QTOOLS:KEYCHORD-EDITOR ..)))))
 35: (FORMAT[error printing frame]
 36: (FORMAT NIL "~s Delegating class options: ~s" #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> (:NAME QTOOLS:KEYCHORD-EDITOR :DIRECT-SUPERCLASSES ..)))))
 37: (ORG.TYMOONNEXT.RADIANCE.LIB.VERBOSE:LOG :DEBUG :QTOOLS.WIDGET "~s Delegating class options: ~s" #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> (:NAME ..)))))
 38: (QTOOLS::SETUP-WIDGET-CLASS #<QTOOLS:WIDGET-CLASS #<error printing QTOOLS:WIDGET-CLASS #x55429D0E> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CALL-NEXT-METHOD ..) :NAME QTOOLS:KEYCHORD-EDITOR :DIRECT-SUPER..
 39: (NIL #<Unknown Arguments>)
 40: (CCL::%%CNM-WITH-ARGS-COMBINED-METHOD-DCODE #(#<STANDARD-GENERIC-FUNCTION INITIALIZE-INSTANCE #x540812A6> (#<STANDARD-METHOD INITIALIZE-INSTANCE :AROUND #> #<#> #<#> #<#> #<#>) ..)) -313422468 NIL)
 41: (NIL #<Unknown Arguments>)
 42: (CCL::%MAKE-STD-INSTANCE #<STANDARD-CLASS QTOOLS:WIDGET-CLASS> (:NAME QTOOLS:KEYCHORD-EDITOR :DIRECT-SUPERCLASSES (#<QTOOLS:WIDGET-CLASS QTOOLS:WIDGET>) :DIRECT-SLOTS ..)))))
 43: (NIL #<Unknown Arguments>)
 44: (#<CCL::STANDARD-KERNEL-METHOD MAKE-INSTANCE (STANDARD-CLASS)> #<STANDARD-CLASS QTOOLS:WIDGET-CLASS> :NAME QTOOLS:KEYCHORD-EDITOR :DIRECT-SUPERCLASSES (#<QTOOLS:WIDGET-CLASS QTOOLS:WIDGET>) :DIRECT-SL..
 45: (#<CCL::STANDARD-KERNEL-METHOD ENSURE-CLASS-USING-CLASS (NULL T)> NIL QTOOLS:KEYCHORD-EDITOR :DIRECT-SUPERCLASSES (QTOOLS:WIDGET) :DIRECT-SLOTS ((:NAME QTOOLS::OLD-ACCELERATOR :INITFORM "" ..)))) :QT-..
 46: (NIL #<Unknown Arguments>)
 47: (CCL::ENSURE-CLASS-FOR-DEFCLASS QTOOLS:KEYCHORD-EDITOR :DIRECT-SUPERCLASSES (QTOOLS:WIDGET) :DIRECT-SLOTS ((:NAME QTOOLS::OLD-ACCELERATOR :INITFORM "" :INITFUNCTION ..)))) :QT-SUPERCLASS ("QDialog") :..
 48: (CCL::$FASL-LFUNCALL #<CCL::FASLSTATE #xB55C5EB6>)
 49: (CCL::%FASLOAD -1 1)
 50: (CCL::%FASLOAD "/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl" #(#<Compiled-function CCL::$FASL-NOOP (Non-Global)  #x5403452E>..
 51: (NIL #<Unknown Arguments>)
 52: (CCL::%LOAD ((#<RESTART CCL::RETRY-LOAD #xB55C6156> #<RESTART CCL::SKIP-LOAD #xB55C617E> #<RESTART CCL::LOAD-OTHER #xB55C61A6>) (#<RESTART ASDF/LISP-ACTION:TRY-RECOMPILING #xB55C6416>) ..))) 188 ((#<R..
 53: (CCL::%LOAD #<Package "COMMON-LISP-USER"> 98 #<Package "QTOOLS"> #<READTABLE #x543832D6> 114 #<NAMED-READTABLE :QT #x551E4446>)
 54: (CCL::%LOAD #P"/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl" NIL NIL :ERROR :DEFAULT NIL)
 55: (NIL #<Unknown Arguments>)
 56: (LOAD ((#<RESTART ASDF/LISP-ACTION:TRY-RECOMPILING #xB55C6416>) (#<RESTART ASDF/FIND-COMPONENT:RETRY #xB55C659E> #<RESTART ASDF/ACTION:ACCEPT #xB55C65C6>) (#<RESTART ABORT #xB55C6C9E>) ..))) :VERBOSE ..
 57: (LOAD #P"/home/ubuntu/.cache/common-lisp/ccl-1.9-f99-linux-arm/home/ubuntu/quicklisp/local-projects/qtools/keychord-editor.lafsl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DE..
 58: (NIL #<Unknown Arguments>)
 59: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<COMPILED-LEXICAL-CLOSURE (:INTERNAL ASDF/LISP-ACTION:PERFORM-LISP-LOAD-FASL) #x5542A92E> ("No generic function ~S present when encountering macroexpansion ..
 60: (NIL #<Unknown Arguments>)
 61: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> . -313422343))
 62: (NIL #<Unknown Arguments>)
 63: (CCL::%%STANDARD-COMBINED-METHOD-DCODE ((#<STANDARD-METHOD ASDF/ACTION:PERFORM :BEFORE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)>) ..))) -313422343)
 64: (NIL #<Unknown Arguments>)
 65: (NIL #<Unknown Arguments>)
 66: (NIL #<Unknown Arguments>)
 67: (CCL::%CALL-NEXT-METHOD[error printing frame]
 68: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (T T)> . -313422293))
 69: (NIL #<Unknown Arguments>)
 70: (#<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> ((#<RESTART ASDF/LISP-ACTION:TRY-RECOMPILING #xB55C6416>) ..))) ((#<RESTART ASDF/FIND-C..
 71: (#<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (T T)> . -313422293) #<LOAD-OP..
 72: (NIL #<Unknown Arguments>)
 73: (CCL::%CALL-NEXT-METHOD[error printing frame]
 74: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (T T)> . -313422293))
 75: (NIL #<Unknown Arguments>)
 76: (#<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)> ((#<RESTART ASDF/FIND-COMPONENT:RETRY #xB55C659E> #<RESTART ASDF/ACTION:ACCEPT #xB55C65C6>) (#<RESTART ABORT #xB55C6C9E>) ..))) ((#<..
 77: (#<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)> (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (T T)> . -313422293) #<LOAD-OP >)
 78: (NIL #<Unknown Arguments>)
 79: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)> ..)) -313422293)
 80: (NIL #<Unknown Arguments>)
 81: (#<STANDARD-METHOD ASDF/PLAN:PERFORM-PLAN (LIST)> ((#<PREPARE-OP > . #<SYSTEM "babel">) (#<PREPARE-OP > . #<MODULE "babel" "src">) (#<PREPARE-OP > . #<CL-SOURCE-FILE "babel" "src" "packages">) ..))))
 82: (NIL #<Unknown Arguments>)
 83: (CCL::%CALL-NEXT-METHOD[error printing frame]
 84: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD ASDF/PLAN:PERFORM-PLAN (LIST)> . -313422251))
 85: (NIL #<Unknown Arguments>)
 86: (CCL::CALL-WITH-COMPILATION-UNIT #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::WITH-COMPILATION-UNIT-BODY (ASDF/PLAN:PERFORM-PLAN :AROUND (T))) #xB55C672E> :OVERRIDE NIL)
 87: (NIL #<Unknown Arguments>)
 88: (#<STANDARD-METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)> (NIL #<STANDARD-METHOD ASDF/PLAN:PERFORM-PLAN (LIST)> . -313422251))
 89: (NIL #<Unknown Arguments>)
 90: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)> #<STANDARD-METHOD ASDF/PLAN:PERFORM-PLAN (LIST)>) -313422251)
 91: (NIL #<Unknown Arguments>)
 92: (NIL #<Unknown Arguments>)
 93: (NIL #<Unknown Arguments>)
 94: (CCL::%%CHECK-KEYWORDS #(1 #() #<Combined-Method ASDF/PLAN:PERFORM-PLAN #x5473A8C6>) -313422245)
 95: (NIL #<Unknown Arguments>)
 96: (#<STANDARD-METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)> #<LOAD-OP :VERBOSE NIL> #<SYSTEM "qtools"> :VERBOSE NIL)
 97: (NIL #<Unknown Arguments>)
 98: (CCL::%CALL-NEXT-METHOD[error printing frame]
 99: (CCL::%CALL-NEXT-METHOD ((NIL) #<STANDARD-METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)> #<LOAD-OP :VERBOSE NIL> #<SYSTEM "qtools"> :VERBOSE NIL))
 100: (NIL #<Unknown Arguments>)
 101: ((:INTERNAL (ASDF/OPERATE:OPERATE :AROUND (T T))))
 102: (NIL #<Unknown Arguments>)
 103: (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :AROUND (T T)>[error printing frame]
 104: (NIL #<Unknown Arguments>)
 105: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :AROUND (T T)> (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :BEFORE #> #<#>) NIL ..))) -313422194)
 106: (NIL #<Unknown Arguments>)
 107: (NIL #<Unknown Arguments>)
 108: (NIL #<Unknown Arguments>)
 109: (CCL::%CALL-NEXT-METHOD[error printing frame]
 110: (CCL::%CALL-NEXT-METHOD ((NIL) #<STANDARD-METHOD ASDF/OPERATE:OPERATE (SYMBOL T)> ASDF/LISP-ACTION:LOAD-OP "qtools" :VERBOSE NIL))
 111: (NIL #<Unknown Arguments>)
 112: ((:INTERNAL (ASDF/OPERATE:OPERATE :AROUND (T T))))
 113: (NIL #<Unknown Arguments>)
 114: (ASDF/CACHE:CALL-WITH-ASDF-CACHE #<COMPILED-LEXICAL-CLOSURE (:INTERNAL (ASDF/OPERATE:OPERATE :AROUND (T T))) #x54C59C0E> :OVERRIDE NIL)
 115: (NIL #<Unknown Arguments>)
 116: (ASDF/FIND-SYSTEM::CALL-WITH-SYSTEM-DEFINITIONS #<COMPILED-LEXICAL-CLOSURE (:INTERNAL (ASDF/OPERATE:OPERATE :AROUND (T T))) #x54C59C0E>)
 117: (NIL #<Unknown Arguments>)
 118: (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :AROUND (T T)>[error printing frame]
 119: (NIL #<Unknown Arguments>)
 120: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :AROUND (T T)> (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :BEFORE #>) NIL ..) -313422134)
 121: (NIL #<Unknown Arguments>)
 122: (NIL #<Unknown Arguments>)
 123: (NIL #<Unknown Arguments>)
 124: (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :AROUND (T T)>[error printing frame]
 125: (NIL #<Unknown Arguments>)
 126: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :AROUND (T T)> (#<STANDARD-METHOD ASDF/OPERATE:OPERATE :BEFORE #>) NIL ..) -313422106)
 127: (NIL #<Unknown Arguments>)
 128: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<COMPILED-LEXICAL-CLOSURE (:INTERNAL QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) #x54C5A056>)
 129: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES ((WARNING #<Compiled-function MUFFLE-WARNING #x5418431E>) (T #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK:EVAL-FOR-EMACS) #x54AD850E>) ..)))) :PROMPT..
 130: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES ((#<RESTART SWANK::RETRY #xB55C709E>) (#<RESTART ABORT #xB55C72C6>) (#<RESTART ABORT-BREAK #xB55C763E> #<RESTART ABORT #xB55C7666>)) :PROMPT 188)
 131: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "qtools" :PROMPT NIL)
 132: (NIL #<Unknown Arguments>)
 133: (#<STANDARD-METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)> #<QL-IMPL:CCL #x5475D2B6> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL QUICKLISP-CLIENT::QL ..))
 134: (#<STANDARD-METHOD QUICKLISP-CLIENT:QUICKLOAD (T)> ("verbose" "qtools") :PROMPT NIL :SILENT NIL :VERBOSE NIL)
 135: (NIL #<Unknown Arguments>)
 136: (CCL::%CALL-NEXT-METHOD[error printing frame]
 137: (CCL::%CALL-NEXT-METHOD ((NIL) #<STANDARD-METHOD QUICKLISP-CLIENT:QUICKLOAD (T)> ("verbose" "qtools")))
 138: (NIL #<Unknown Arguments>)
 139: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<COMPILED-LEXICAL-CLOSURE (:INTERNAL (QUICKLISP-CLIENT:QUICKLOAD :AROUND (T))) #x54AD82B6>)
 140: (NIL #<Unknown Arguments>)
 141: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD QUICKLISP-CLIENT:QUICKLOAD :AROUND (T)> #<STANDARD-METHOD QUICKLISP-CLIENT:QUICKLOAD (T)>) -313422015)
 142: (NIL #<Unknown Arguments>)
 143: (NIL #<Unknown Arguments>)
 144: (NIL #<Unknown Arguments>)
 145: (CCL::CALL-CHECK-REGS QUICKLISP-CLIENT:QUICKLOAD ("verbose" "qtools"))
 146: (NIL #<Unknown Arguments>)
 147: (CCL::CHEAP-EVAL (QUICKLISP-CLIENT:QUICKLOAD '("verbose" "qtools")))
 148: (NIL #<Unknown Arguments>)
 149: (SWANK::EVAL-REGION -1)
 150: (SWANK::EVAL-REGION "(ql:quickload '(\"verbose\" \"qtools\"))\n")
 151: (NIL #<Unknown Arguments>)
 152: ((:INTERNAL SWANK-REPL::REPL-EVAL))
 153: (NIL #<Unknown Arguments>)
 154: (SWANK-REPL::TRACK-PACKAGE -1)
 155: (SWANK-REPL::TRACK-PACKAGE #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x54AD848E>)
 156: (NIL #<Unknown Arguments>)
 157: (SWANK::CALL-WITH-RETRY-RESTART ((#<RESTART ABORT #xB55C72C6>) (#<RESTART ABORT-BREAK #xB55C763E> #<RESTART ABORT #xB55C7666>)) 188)
 158: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x54AD84CE>)
 159: (NIL #<Unknown Arguments>)
 160: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x54AD84EE>)
 161: (SWANK-REPL::REPL-EVAL "(ql:quickload '(\"verbose\" \"qtools\"))\n")
 162: (NIL #<Unknown Arguments>)
 163: (CCL::CALL-CHECK-REGS SWANK-REPL:LISTENER-EVAL "(ql:quickload '(\"verbose\" \"qtools\"))\n")
 164: (NIL #<Unknown Arguments>)
 165: (CCL::CHEAP-EVAL (SWANK-REPL:LISTENER-EVAL "(ql:quickload '(\"verbose\" \"qtools\"))\n"))
 166: (SWANK:EVAL-FOR-EMACS -1 1 0)
 167: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(ql:quickload '(\"verbose\" \"qtools\"))\n") "COMMON-LISP-USER" 13)
 168: (SWANK::PROCESS-REQUESTS NIL)
 169: (NIL #<Unknown Arguments>)
 170: ((:INTERNAL SWANK::HANDLE-REQUESTS))
 171: ((:INTERNAL SWANK::HANDLE-REQUESTS))
 172: ((:INTERNAL SWANK::HANDLE-REQUESTS))
 173: ((:INTERNAL SWANK::HANDLE-REQUESTS))
 174: (NIL #<Unknown Arguments>)
 175: (SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK #<Compiled-function SWANK:SWANK-DEBUGGER-HOOK #x549AD8E6> #<COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK::HANDLE-REQUESTS) #x54AD2FC6>)
 176: (NIL #<Unknown Arguments>)
 177: (SWANK::CALL-WITH-BINDINGS NIL NIL)
 178: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-OUTPUT* . #<SWANK/GRAY::SLIME-OUTPUT-STREAM #x54AC8CA6>) (*STANDARD-INPUT* . #<SWANK/GRAY::SLIME-INPUT-STREAM #x54AC8DEE>) ..)) #<COMPILED-LEXICAL-CLOSURE (:INTE..
 179: (NIL #<Unknown Arguments>)
 180: (SWANK::HANDLE-REQUESTS ((PROCESS-RESET)) 60)
 181: (SWANK::HANDLE-REQUESTS #<MULTITHREADED-CONNECTION #x549FABF6> NIL)
 182: (NIL #<Unknown Arguments>)
 183: (CCL::RUN-PROCESS-INITIAL-FORM #<Unprintable CCL::IMMEDIATE : #xF3> 188)
 184: (CCL::RUN-PROCESS-INITIAL-FORM #<Unprintable CCL::IMMEDIATE : #xF3> 60)
 185: (CCL::RUN-PROCESS-INITIAL-FORM #<PROCESS repl-thread(12) [Active] #x54AC8FBE> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x54AC8E96>))
 186: (NIL #<Unknown Arguments>)
 187: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS))) -1 1)
 188: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS))) -1 1)
 189: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS))) #<PROCESS repl-thread(12) [Active] #x54AC8FBE> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x54AC8E96>))
 190: ((:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION))
 191: (NIL #<Unknown Arguments>)
 192: (NIL #<Unknown Arguments>)

**Comment by Shinmera** [comment]
Why did you close it? Does it work now or what?

**Comment by vr3dc** [comment]
No, sorry. I'm just a github novice. I hit the wrong button. I did want to say that it didn't work when I loaded verbose (which also looks excellent)

**Comment by vr3dc** [comment]
The function (defmethod c2mop:compute-effective-slot-definition...  
;Compiler warnings :
;   In (CCL:COMPUTE-EFFECTIVE-SLOT-DEFINITION (FINALIZABLE-CLASS T T)) inside an anonymous lambda form: Unused lexical variable NAME
#<STANDARD-METHOD CCL:COMPUTE-EFFECTIVE-SLOT-DEFINITION (FINALIZABLE-CLASS T T)>

I just modified the ccl function with a (declare (ignore name)) and QTools compiled. 

Your use of declare for connecting the GUI actions is masterful. At first glance it looks like something that shouldn't work.

Thanks again. this time I am closing the issue.

**Comment by Shinmera** [comment]
That it doesn't use a lexical variable isn't a stopping error though and thus can't be the cause of a load failure. I'm guessing that the problem was stale FASLs somewhere, which upon changing the file ASDF discarded.
