### ISSUE TITLE
Can't build some systems - missing foreign libraries?

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/qtools#13]
http://report.quicklisp.org/2016-05-19/failure-report/qtools.html has some regressions. Are these newly required foreign libraries or something?

**Comment by Shinmera** [comment]
They're not newly required, just loaded differently now. Previously it was mostly up to the underlying OS to find the libraries and their transitive dependencies, which lead to a problem where bad versions were loaded from an unexpected place. Qtools now loads them through explicit paths, but that might have introduced new problems.

For debian, installing libphonon-dev, libqimageblitz-dev, and libqscintilla2-dev should fix at least three of the failures. The qtmultimedia one I'm not sure about. On my debian system the QtMultimedia lib is completely missing, which is very bizarre. I might end up removing that system altogether if it simply isn't provided by some distributions.

**Comment by quicklisp** [comment]
I build everything from scratch, with no fasl cache, each time.

I'll install the libraries you recommend and see how it goes.

I don't have libQtMultimedia.so and I don't see it available via apt-file, though.

**Comment by Shinmera** [comment]
Right, that's the weird thing I found on my debian server as well. I think I'll just remove the system, I doubt anyone actually uses it.
