### ISSUE TITLE
Some systems don't build for me today

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/qtools#18]
http://report.quicklisp.org/2016-12-04/failure-report/qtools.html has a log...not sure what's up, sorry.

**Comment by quicklisp** [comment]
That fixes everything except qthelp.

**Comment by Shinmera** [comment]
Is the failure text for that the same still?

**Comment by quicklisp** [comment]
Unhandled CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {100207F5C3}>: Unable to load foreign library (QTHELP).
      Error opening shared object "/home/quicklisp/quicklisp-controller/dist/build-cache/qt-libs/29f28ae9703dac09dfc7575f575fd90298ef1fcd/qt-libs-20161205-git/standalone/qtlibs!QtHelp.so":
      qtlibs!QtCLucene.so: cannot open shared object file: No such file or directory.

Log here: http://report.quicklisp.org/2016-12-05/failure-report/qtools.html#qthelp

**Comment by Shinmera** [comment]
The load order of the library files for it was messed up. Should be fixed now, too.
