### ISSUE TITLE
define-subobejct macro doesn't work well

### ISSUE THREAD

**Issue by maiego** [Shinmera/qtools#21]
In widget-convenience.lisp file.

```
(defmacro define-subobject ((object-class name) initform &body body)
  `(define-subwidget ((,object-class ,name) ,initform ,@body)))
```

I think arg for define-subwidget should be

`(,object-class ,name) ,initform ,@body`

without additional wrapping ()

and actually error of parsing macro arguments occured when use define-subobject.

p.s.
I appreciate you for making such great work.
however, I feel need for more documentation or tutorial to use this library.
maybe I might have to study commonqt or Qt with C++ more...

**Comment by Shinmera** [comment]
Sure, that's an easy fix. I never had the need for `define-subobject` before, so I never caught it in testing.

The documentation for this library is [already very extensive](https://shinmera.github.io/qtools/). What are you missing?
