### ISSUE TITLE
Commonqt load fails on Allegro modern-mode

### ISSUE THREAD

**Issue by genworks** [Shinmera/qtools#26]
Hi,

 I'm writing here because I don't see an Issues list for Commonqt itself. 

Commonqt and several of its dependencies have some uses of NIL and T (uppercase), which break Allegro CL modern-mode. Fixing this appears to be a fairly simple matter of search-and-replace of T with t and NIL with nil. If the maintainers would be interested in supporting a modern-mode Lisp, I can prepare a patch with the fixes (for now I've just locally modified the necessary files to get things to load). 

There are one or two other issues on Allegro to do with the :version attribute of make-pathname - I can include those as well if desired. 

For some reason my Mac installation also did not automatically build the libcommonqt.dylib -- the `(ql:quickload :commonqt)` did detect Brew and appeared to install several dylib's under qt-libs-20171227-git/standalone/ (looks like an impressive amount of install automation so far!), but the build step of libcommonqt.dylib didn't happen for some reason. But first things first  ---  before diving further into the dylib issue I'd like to confirm that the maintainers will be open to the modern-mode patch. 

Thanks,

 Dave

**Comment by Shinmera** [comment]
Allegro is not listed as a [supported implementation](https://github.com/Shinmera/qtools#support).

That aside, I refuse, out of principle, to support other readtable cases than upcase. Practically none of my libraries will work with non-default readtable cases.

It should not build libcommonqt.dylib as that should be shipped automatically.
