### ISSUE TITLE
Error and freeze when creating window in Win10/SBCL

### ISSUE THREAD

**Issue by ntrocado** [Shinmera/qtools#30]
After quickloading the library I followed the example in the readme. But (with-main-window (window 'main-window)) doesn't create any window, produces the warnings below, and freezes.
I checked that the files exist, but not in the mentioned path. debug.lisp is on …../uiop-3.3.1/ (there is no 'contrib' subfolder). The dlls are all in the 'standalone' subfolder, not 'system'.

QTOOLS-INTRO> (with-main-window (window 'main-window))
WARNING:
   compiling #<STATIC-FILE "uiop" "contrib/debug.lisp"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/uiop-3.3.1/contrib/debug.lisp"
WARNING:
   loading #<STATIC-FILE "uiop" "contrib/debug.lisp"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/uiop-3.3.1/contrib/debug.lisp"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "smokebase" "smokebase"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokebase.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "smokebase" "smokebase"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokebase.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "commonqt" "QtCore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtCore.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "commonqt" "QtCore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtCore.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "commonqt" "QtGui"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtGui.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "commonqt" "QtGui"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtGui.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "commonqt" "commonqt"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/commonqt.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "commonqt" "commonqt"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/commonqt.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "qtcore" "QtCore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtCore.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "qtcore" "QtCore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtCore.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "qtcore" "smokeqtcore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokeqtcore.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "qtcore" "smokeqtcore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokeqtcore.dll"
WARNING:
   compiling #<STATIC-FILE "uiop" "contrib/debug.lisp"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/uiop-3.3.1/contrib/debug.lisp"
WARNING:
   loading #<STATIC-FILE "uiop" "contrib/debug.lisp"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/uiop-3.3.1/contrib/debug.lisp"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "smokebase" "smokebase"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokebase.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "smokebase" "smokebase"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokebase.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "commonqt" "QtCore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtCore.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "commonqt" "QtCore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtCore.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "commonqt" "QtGui"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtGui.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "commonqt" "QtGui"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtGui.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "commonqt" "commonqt"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/commonqt.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "commonqt" "commonqt"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/commonqt.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "qtcore" "QtCore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtCore.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "qtcore" "QtCore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtCore.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "qtcore" "smokeqtcore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokeqtcore.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "qtcore" "smokeqtcore"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokeqtcore.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "qtgui" "QtGui"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtGui.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "qtgui" "QtGui"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/QtGui.dll"
WARNING:
   compiling #<FOREIGN-LIBRARY-COMPONENT "qtgui" "smokeqtgui"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokeqtgui.dll"
WARNING:
   loading #<FOREIGN-LIBRARY-COMPONENT "qtgui" "smokeqtgui"> completed without its input file #P"c:/Users/trocado/AppData/Roaming/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/systems/smokeqtgui.dll"

**Comment by ntrocado** [comment]
I tried copying the files to their expected places, (and also renamed QtCore4.dll to QtCore.dll and QtGui4.dll to QtGui.dll). The warnings are gone, but still no window.

**Comment by Shinmera** [comment]
The warnings are a red herring and don't mean anything. Check *inferior-lisp* to see if there's anything there.

**Comment by phoe** [comment]
Anything visible in the inferior-lisp buffer?

July 23, 2018 11:13 AM, "ntrocado" <notifications@github.com (mailto:%22ntrocado%22%20<notifications@github.com>)> wrote:
	I tried copying the files to their expected places, (and also renamed QtCore4.dll to QtCore.dll and QtGui4.dll to QtGui.dll). The warnings are gone, but still no window.

**Comment by ntrocado** [comment]
There's nothing relevant in the inferior-lisp buffer.
Meanwhile I checked that this is indeed working on bare SBCL (before I was using Sly, running stuff from the repl).

**Comment by Shinmera** [comment]
Ah, I see. I think Sly uses its own version of Swank that doesn't push the swank feature, which means this fix is not applied: https://github.com/Shinmera/qtools/blob/master/toolkit.lisp#L292

**Comment by phoe** [comment]
Perhaps s/#+(and swank windows)/#+(and (or swank slynk) windows)/ ? (I assume the relevant feature is named SLYNK.)

July 23, 2018 12:05 PM, "Nicolas Hafner" <notifications@github.com (mailto:%22Nicolas%20Hafner%22%20<notifications@github.com>)> wrote:
	Ah, I see. I think Sly uses its own version of Swank that doesn't push the swank feature, which means this fix is not applied: https://github.com/Shinmera/qtools/blob/master/toolkit.lisp#L292 (https://github.com/Shinmera/qtools/blob/master/toolkit.lisp#L292)

**Comment by ntrocado** [comment]
Simply `(push :swank *features*)` doesn't do it...

**Comment by Shinmera** [comment]
Well obviously not because it was compile-time selected. Either try the latest git head, or force a recompile after pushing the feature.

**Comment by ntrocado** [comment]
I can confirm that the window is now spawning using Sly. Thank you!
