### ISSUE TITLE
titter example creds 

### ISSUE THREAD

**Issue by juszczakn** [Shinmera/qtools#31]
I assume these twitter creds aren't valid, but might make sense to make it obvious they are invalid with a comment or somesuch? 

https://github.com/Shinmera/qtools/blob/master/examples/titter/titter.lisp#L20

**Comment by phoe** [comment]
Why don't you simply `(defvar *twitter-application-key*)`? That should force anyone using the code to set it for themselves.

July 27, 2018 5:28 AM, "Nick" <notifications@github.com (mailto:%22Nick%22%20<notifications@github.com>)> wrote:
	I assume these twitter creds aren't valid, but might make sense to make it obvious they are invalid with a comment or somesuch? 

	https://github.com/Shinmera/qtools/blob/master/examples/titter/titter.lisp#L20 (https://github.com/Shinmera/qtools/blob/master/examples/titter/titter.lisp#L20)

**Comment by Shinmera** [comment]
They [are valid](http://shinmera.github.io/chirp/).
