### ISSUE TITLE
How would you load an image and display it?

### ISSUE THREAD

**Issue by jsalzbergedu** [Shinmera/qtools#38]
I've tried:
```lisp
(named-readtables:in-readtable :qtools)

(define-widget main (QWidget)
  ())

(define-subwidget (main label)
    (let ((label (q+:make-qlabel))
          (pixmap (q+:make-qpixmap)))
      (q+:load pixmap ...)
      (print (format t "pixmap is null? ~A" (q+:is-null pixmap)))
      (q+:set-pixmap label pixmap)
      label))

(defun app-main ()
  (with-main-window (window (make-instance 'main))))
```
Then ran app-main, found out that the pixmap is not null, yet saw nothing but an empty pane. So how would you load an image and display it?

Thanks.

**Comment by phoe** [comment]
The subwidget is not added to the layout of `main` and therefore it is not drawn. Simply defining a subwidget does not make it visible or added to any layouts; you must do it manually.

A roughly done and untested example:

```common-lisp
(define-subwidget (main layout) (q+:make-qvboxlayout main))

(define-subwidget (main label)
  ...
  (q+:add-widget layout label))
```

**Comment by jsalzbergedu** [comment]
Lol thank you I suspected that I was just being unintelligent

**Comment by phoe** [comment]
Not really unintelligent, I would say - if you're only learning the framework and Qt right now, then it's obvious that you'll need some help now and then.
