### ISSUE TITLE
"#1# is not a symbol or lambda expression." on Windows with CCL

### ISSUE THREAD

**Issue by nandryshak** [Shinmera/qtools#4]
I have a file like this:
    
    (ql:quickload '(:qtools :qtcore :qtgui))

    (defpackage #:qtools-intro
      (:use #:cl+qt)
      (:export #:main))

    (in-package #:qtools-intro)
    (named-readtables:in-readtable :qtools)

    (define-widget main-window (QWidget)
      ())

    (with-main-window (window (make-instance 'main-window)))

When loading it with `ccl -l test.lisp` I get this error:
    
    While compiling an anonymous function :
    In the form (#1=(:UNDERFLOW :OVERFLOW :INVALID :INEXACT) PROGN
                 (QTOOLS:WITH-FINALIZING
                   ((QTOOLS-INTRO::WINDOW
                     (QTOOLS:ENSURE-QOBJECT
                       (MAKE-INSTANCE 'QTOOLS-INTRO::MAIN-WINDOW))))
                   ((LAMBDA NIL
                      (QT:OPTIMIZED-CALL
                        T
                        QTOOLS-INTRO::WINDOW
                        "show")))
                   ((LAMBDA NIL
                      (QT:OPTIMIZED-CALL
                        T
                        QT:*QAPPLICATION*
                        "exec"))))), #1# is not a symbol or lambda expression.
       [Condition of type CCL::COMPILE-TIME-PROGRAM-ERROR]

Using Clozure Common Lisp Version 1.10-r16196  (WindowsX8632)

However, simply using CommonQt works fine:
 
    (ql:quickload :qt)
    (named-readtables:in-readtable :qt)
    (qt:with-main-window (window (#_new QWidget)))

**Comment by Shinmera** [comment]
Are you using the latest Quicklisp dist version?

**Comment by nandryshak** [comment]
Yes I am, just installed everything Qt related today. I think this problem may be namespace/package related, maybe on my part. This works fine:

    (ql:quickload :qtools)
    (named-readtables:in-readtable :qtools)
    (qtools:define-widget main-window (QWidget)
      ())
    (qt:with-main-window (window (make-instance 'main-window)))

**Comment by Shinmera** [comment]
If I am correct in interpreting the error it's with an obscure reader macro related thing in the with-main-window macro. Try cloning from git and see if that works.

**Comment by nandryshak** [comment]
Cloning `qt-libs` and `qtools` from git works, thanks!

**Comment by Shinmera** [comment]
The next QL release should be on the coming weekend, so you should be able to switch back away from GIT then.
