### ISSUE TITLE
Build executable: Component :SYSTEM-NAME not found

### ISSUE THREAD

**Issue by autcrock** [Shinmera/qtools#41]
Hi Nicolas.

Happy New Year and thanks for the great work you do.

On both Debian Linux and Windows 10 with 64 bit SBCL 2.0.0, building a QTools executable per the QTools instructions fails as reported below.

Cheers

Mike Thomas

=============================================
mjt@snowpeaD:~/quicklisp/dists/quicklisp/software/qtools-20191130-git/examples/helloworld$ sbcl --eval "(asdf:operate :build-op :system-name :force T)"
This is SBCL 2.0.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

debugger invoked on a ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread
#<THREAD "main thread" RUNNING {10005184C3}>:
  Component :SYSTEM-NAME not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry ASDF operation.
  1: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  2:                                 Retry ASDF operation.
  3:                                 Retry ASDF operation after resetting the
                                     configuration.
  4: [CONTINUE                     ] Ignore runtime option --eval "(asdf:operate :build-op :system-name :force T)".
  5: [ABORT                        ] Skip rest of --eval and --load options.
  6:                                 Skip to toplevel READ/EVAL/PRINT loop.
  7: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

((:METHOD ASDF/OPERATE:OPERATE (SYMBOL T)) :BUILD-OP :SYSTEM-NAME :FORCE T) [fast-method]
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0]

**Comment by phoe** [comment]
You need to replace `:system-name` with the name of your system to be built.

**Comment by autcrock** [comment]
Much appreciated Phoe - it works now!

    sbcl --eval "(asdf:operate :build-op 'qtools-helloworld :force T)"
