### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/qtools#48]
Building with SBCL 2.3.1.43-c2e7dcbd6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 0f10649913ed74afa356b3ade9ed0d33aa779f33

*q+* fails to build because of a failure in  _qtools_.

*qtools-evaluator* fails to build because of a failure in  _qtools_.

*qtools-game* fails to build because of a failure in  _qtools_.

*qtools-helloworld* fails to build because of a failure in  _qtools_.

*qtools-melody* fails to build because of a failure in  _qtools_.

*qtools-opengl* fails to build because of a failure in  _qtools_.

*qtools-titter* fails to build because of a failure in  _qtools_.

*qtools* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: The symbol "FUNCTION" is not external in the CL+QT package. Line: 106, Column: 24, File-Position: 4162 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/qtools/500e27aeb057a8fd6a9ecdf77aeb74f6410a02aa/qtools-20230205-git/dynamic.lisp" {10108D0433}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001720003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "qtools" "dynamic">

```

[Full log here](http://report.quicklisp.org/2023-02-05/failure-report/qtools.html)

**Comment by Shinmera** [comment]
How bizarre. I can't reproduce on SBCL 2.3.1. Loading qtools flushes through just fine with `:verbose T`. The code in this has not changed in many years, either.

**Comment by quicklisp** [comment]
Hmm, I'm using newer than 2.3.1, maybe there's a package bug in it. I'll
investigate more.

**Comment by quicklisp** [comment]
Doug Katzman pointed out that the current code runs afoul of
http://l1sp.org/cl/3.6 with regard to traversing packages. He suggests
replacing it with:

(let (list) (do-symbols (s "CL+QT") (push s list))
  (export list "CL+QT"))

This allows qtools to compile again on the latest SBCL HEAD.

Zach
